# Copyright (C) 2022 Intel Corp.
# 
# SPDX-License-Identifier: Apache-2.0

[[DeviceList]]
  Name = "pos-mqtt"
  ProfileName = "pos"
  Description = "MQTT device for POS"
  Labels = [ "MQTT", "pos"]
  [DeviceList.Protocols]
    [DeviceList.Protocols.mqtt]
       CommandTopic = "EdgeXPosCommand"
[[DeviceList]]
  Name = "scale-mqtt"
  ProfileName = "scale"
  Description = "MQTT device for Scale"
  Labels = [ "MQTT", "scale"]
  [DeviceList.Protocols]
    [DeviceList.Protocols.mqtt]
       CommandTopic = "EdgeXScaleCommand"
[[DeviceList]]
  Name = "rfid-roi-mqtt"
  ProfileName = "rfid-roi"
  Description = "MQTT device for RFID ROI events"
  Labels = [ "MQTT", "rfid"]
  [DeviceList.Protocols]
    [DeviceList.Protocols.mqtt]
       CommandTopic = "EdgeXRfidCommand"
[[DeviceList]]
  Name = "cv-roi-mqtt"
  ProfileName = "cv-roi"
  Description = "MQTT device for CV ROI events"
  Labels = [ "MQTT", "cv", "ROI"]
  [DeviceList.Protocols]
    [DeviceList.Protocols.mqtt]
       CommandTopic = "EdgeXRoiCommand"