runner:
  bandit:
    cmd:  'bandit -r ./ -f custom --msg-template "{relpath}:{line}:{col}:{test_id}:{severity}:{msg}" | tee "$PWD"/scan_results/banditResults.txt' 
    errorformat: # (optional if you use `format`)
      - "%f:%l:%c:%m" 
    name: bandit # (optional. you can overwrite <tool-name> defined by runner key)
    level: info # (optional. same as -level flag. [info,warning,error])
  hadolint:
    cmd: 'make hadolint && cat go-lint.json | jq -f ".github/.rdjson.jq" -c | tee "$PWD"/scan_results/hadolintResults.txt'
    format: rdjson
    level: error # (optional. same as -level flag. [info,warning,error])
  pep8:
    cmd: pep8 rtsf-at-checkout-cv-region-of-interest/src/**/*.py | tee "$PWD"/scan_results/pep8Results.txt
    format: pep8
  golangci-lint:
    cmd: make go-lint
    format: golangci-lint
