# Copyright (C) 2022 Intel Corp.
# 
# SPDX-License-Identifier: Apache-2.0

[[DeviceList]]
  Name = "cas-ed-15-001"
  ProfileName = "cas-scale"
  Description = "CAS ED-15 serial weight scale"
  Labels = [ "cas", "ed-15", "scale", "serial" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.serial]
      VID = "0403"
      PID = "6001" 
  [[DeviceList.AutoEvents]]
    Interval = "1s"
    OnChange = true
    SourceName = "weight"
# [[DeviceList]]
#  Name = "cas-pd-2z-001"
#  ProfileName = "cas-scale"
#  Description = "CAS PD-2Z serial weight scale"
#  Labels = [ "cas", "pd-2z", "scale", "serial" ]
#  [DeviceList.Protocols]
#    [DeviceList.Protocols.serial]
#      VID = "0403"
#      PID = "TBD" 
#  [[DeviceList.AutoEvents]]
#    Interval = "1s"
#    OnChange = true
#    SourceName = "weight"
