# Copyright (C) 2019 - 2022 Intel Corp.
# 
# SPDX-License-Identifier: Apache-2.0

[Writable]
LogLevel = 'INFO'
    [Writable.InsecureSecrets]
        [Writable.InsecureSecrets.DB]
        path = "redisdb"
            [Writable.InsecureSecrets.DB.Secrets]
            username = ""
            password = ""

[Service]
HealthCheckInterval = '10s'
Host = 'localhost'
MaxRequestSize = 0
MaxResultCount = 0
Port = 48096
RequestTimeout = '30s'
ServerBindAddr = ""
StartupMsg = 'Starting Loss Detector'

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'


[Clients]
  # Used for version check on start-up
  [Clients.core-metadata]
  Protocol = "http"
  Host = "localhost"
  Port = 59881

  # Used for Notification and Subscription clients
  [Clients.support-notifications]
  Protocol = "http"
  Host = "localhost"
  Port = 59860


[Trigger]
Type="edgex-messagebus"
  [Trigger.EdgexMessageBus]
  Type = "mqtt"
    [Trigger.EdgexMessageBus.SubscribeHost]
    Host = "localhost"
    Port = 1883
    Protocol = "tcp"
    SubscribeTopics="edgex/events/#"
    [Trigger.EdgexMessageBus.Optional]
    authmode = "none"
    ClientId ="loss-detector"
    Qos =  "0" # Quality of Sevice values are 0 (At most once), 1 (At least once) or 2 (Exactly once)
    KeepAlive =  "10" # Seconds (must be 2 or greater)
    Retained = "false"
    AutoReconnect = "true"
    ConnectTimeout = "5" # Seconds
    SkipCertVerify = "false"
        
[LossDetector]
NotificationEmailAddresses = "cloud@abc.def,jack@abc.def"
NotificationName = "sys-admin"
NotificationReceiver   = "SystemAdministrator"
SecurityCategory       = "SECURITY"
SubscriptionAdminState = "UNLOCKED"
