# Copyright (C) 2019 - 2022 Intel Corp.
# 
# SPDX-License-Identifier: Apache-2.0

[Writable]
LogLevel = 'INFO'
    [Writable.InsecureSecrets]
        [Writable.InsecureSecrets.DB]
        path = "redisdb"
            [Writable.InsecureSecrets.DB.Secrets]
            username = ""
            password = ""

[Service]
HealthCheckInterval = '10s'
Host = 'localhost'
Port = 48095
StartupMsg = 'Event Reconciler has started'
RequestTimeout = '30s'
MaxRequestSize = 0
ServerBindAddr = ""
MaxResultCount = 0

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Clients]
  [Clients.core-metadata]
  Protocol = "http"
  Host = "localhost"
  Port = 59881

[Trigger]
Type= "edgex-messagebus"
  [Trigger.EdgexMessageBus]
  Type = "mqtt"
    [Trigger.EdgexMessageBus.SubscribeHost]
    Host = "localhost"
    Port = 1883
    Protocol = "tcp"
    SubscribeTopics="edgex/events/#"
    [Trigger.EdgexMessageBus.Optional]
    authmode = "none"
    ClientId ="event-reconciler"
    Qos =  "0" # Quality of Sevice values are 0 (At most once), 1 (At least once) or 2 (Exactly once)
    KeepAlive =  "10" # Seconds (must be 2 or greater)
    Retained = "false"
    AutoReconnect = "true"
    ConnectTimeout = "5" # Seconds
    SkipCertVerify = "false"

[Reconciler]
  DeviceNames = "device-pos-rest, device-pos-mqtt, device-scale, device-scale-rest, device-scale-mqtt, device-cv-roi-rest, device-cv-roi-mqtt, device-rfid-roi-rest, device-rfid-roi-mqtt"
  DevicePos = "device-pos"
  DeviceScale = "device-scale"
  DeviceCV = "device-cv-roi"
  DeviceRFID = "device-rfid-roi"
  ProductLookupEndpoint = "localhost:8083"
  WebSocketPort = "9083"
  ScaleToScaleTolerance = 0.02
  CvTimeAlignment = '5s'
